# Generated by Django 4.0.3 on 2022-04-05 09:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Philantropist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия пользователя')),
                ('about_me_philantropist', models.TextField(verbose_name='О себе')),
                ('size_donations', models.IntegerField(default=0, verbose_name='Размер пожертвований')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('registrarion_date_philantropist', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя подопечного')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия подопечного')),
                ('size_donations', models.IntegerField(default=0, verbose_name='Размер пожертвований')),
                ('about_me_ward', models.TextField(verbose_name='О себе')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('registrarion_date_ward', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
