# Generated by Django 4.0.3 on 2022-04-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='size_donations',
        ),
    ]
