# Generated by Django 4.0.3 on 2022-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0002_remove_ward_size_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='address_ward',
            field=models.TextField(default='Не заполнено', verbose_name='Адрес проживания'),
        ),
    ]
