# Generated by Django 4.0.3 on 2022-04-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0002_alter_philantropist_phone_alter_ward_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='philantropist',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус пользователя'),
        ),
        migrations.AddField(
            model_name='ward',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус пользователя'),
        ),
        migrations.AlterField(
            model_name='philantropist',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
