# Generated by Django 4.0.3 on 2022-04-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0003_philantropist_status_ward_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philantropist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='status',
        ),
    ]
