# Generated by Django 4.0.3 on 2022-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0005_alter_philantropist_about_me_philantropist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
    ]
